🆕 SDG pagina feature
KaanKalmi/CrossMarx-S11 pull request #25
Opened 2024-05-24 08:17 UTC by RubenErhardt

## Waar moet je op letten 
- Let op de buttons, als het goed is moet de knop als je klikt een geluidje afspelen
- Let op het vinkje als je een geselecteerde SDG aanklikt, is het duidelijk zichtbaar dat een sdg is geselecteed
- Test de responsiveness van de website 

## Screenshots 
### Desktop
![Screenshot 2024-05-24 100535](https://github.com/KaanKalmi/CrossMarx-S11/assets/144007147/7ad47c56-125f-4e5d-b8a0-dd6a0ae0554c)
![Screenshot 2024-05-24 100554](https://github.com/KaanKalmi/CrossMarx-S11/assets/144007147/76067940-4297-4886-a969-3e6854cd5f39)

### Mobile
![Screenshot 2024-05-24 100315](https://github.com/KaanKalmi/CrossMarx-S11/assets/144007147/30e18611-d1f7-4baa-8a93-310305827e01)

![Screenshot 2024-05-24 100322](https://github.com/KaanKalmi/CrossMarx-S11/assets/144007147/937c74a8-cb4d-4ed0-8dd0-a8cb43ebd22f)

## Code afspraken
https://github.com/KaanKalmi/CrossMarx-S11/wiki#rules

## Oplossing van issue 
#11

2024-05-24 08:21 UTC, IvarSchuyt commented on public/styles/style.css
> +}
Ik zou rem/em doen ipv pixels

2024-05-24 08:23 UTC, IvarSchuyt commented on views/partials/sdgs-login.ejs
> +          </label>
Super responsive en op performance gelet!!!!

2024-05-24 08:25 UTC, IvarSchuyt commented on public/styles/style.css
> +    padding: 0; /* Remove any default padding */
Waarschijnlijk overbodig door global styling (met *)

2024-05-28 10:58 UTC, Anna-Kyra requested changes
Bij je sdg pagina heb je is er nog geen `<form>` aanwezig.
die `<form>` kan om alles heen of ipv het article
Ook is het de mogelijkheid om nog een fieldset eraan toe te voegen.

De overslaan button moet een `type='button'` hebben anders is het bij default een submit button.

De buttons zijn wel erg nice, handig om ze over de hele site deze button toe te voegen als feature. 
Misschien wel handig om een terug button bij deze buttons aan toe te voegen, zodat de gebruiker ook weer terug kan in het document.

2024-05-28 11:12 UTC, RubenErhardt commented
Zal ik dan nog een branch maken voor de buttons?

2024-05-28 11:14 UTC, RubenErhardt commented
> Zal ik dan nog een branch maken voor de buttons?

of is dat heel overbodig

2024-05-28 11:17 UTC, Anna-Kyra reviewed
> Zal ik dan nog een branch maken voor de buttons?

Een andere branch is goed ja! Als feature ook goed voor bewijslast.
Tot nu toe staat de score-form en de login in main, dus daar kunnen de buttons al staat

2024-05-29 08:58 UTC, merged